### ISSUE TITLE
/warps throws up error when essentials converter is enabled

### ISSUE THREAD

**Issue by kennethlinzj** [XZot1K/HyperDrive#3]
Am on the latest Paper Spigot 1.14.4 (#166).

> [07:25:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warps' in plugin HyperDrive v5.1.6-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Paper-latest.jar:git-Paper-166]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[Paper-latest.jar:git-Paper-166]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[Paper-latest.jar:git-Paper-166]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: UUID cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[Paper-latest.jar:git-Paper-166]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.getOfflinePlayer(CraftServer.java:1419) ~[Paper-latest.jar:git-Paper-166]
        at xzot1k.plugins.hd.api.Manager.buildWarpIcon(Manager.java:610) ~[?:?]
        at xzot1k.plugins.hd.api.Manager.buildListMenu(Manager.java:834) ~[?:?]
        at xzot1k.plugins.hd.core.internals.cmds.MainCommands.openListMenu(MainCommands.java:772) ~[?:?]
        at xzot1k.plugins.hd.core.internals.cmds.MainCommands.onCommand(MainCommands.java:113) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Paper-latest.jar:git-Paper-166]
        ... 17 more

**Comment by XZot1K** [comment]
This was adjusted and fixed for 5.1.6 release!

**Comment by XZot1K** [comment]
This issue has been closed due to the issue being completely resolved for the update coming out later today.

**Comment by kennethlinzj** [comment]
Updated to the latest version of HyperDrive. A similar error is thrown up:

> [06:51:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warps' in plugin HyperDrive v5.1.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Paper-latest.jar:git-Paper-166]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[Paper-latest.jar:git-Paper-166]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[Paper-latest.jar:git-Paper-166]        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1134) ~[Paper-latest.jar:git-Paper-166]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[Paper-latest.jar:git-Paper-166]        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at xzot1k.plugins.hd.api.Manager.buildWarpIcon(Manager.java:630) ~[?:?]
        at xzot1k.plugins.hd.api.Manager.buildListMenu(Manager.java:835) ~[?:?]
        at xzot1k.plugins.hd.core.internals.cmds.MainCommands.openListMenu(MainCommands.java:772) ~[?:?]
        at xzot1k.plugins.hd.core.internals.cmds.MainCommands.onCommand(MainCommands.java:113) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Paper-latest.jar:git-Paper-166]
        ... 17 more

**Comment by XZot1K** [comment]
Seems to be due to a warp having a invalid owner. I'll take a look at the warp loading to force bypass these issues, but that may have been due to a invalid owner from the conversation

**Comment by kennethlinzj** [comment]
/warps now work, but clicking on a warp does not do anything and causes this error to appear every second in console:

> [09:55:15 WARN]: [HyperDrive] Task #1245 for HyperDrive v5.1.8 generated an exception
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[Paper-latest.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.getWorld(CraftServer.java:1079) ~[Paper-latest.jar:git-Paper-175]
        at xzot1k.plugins.hd.api.objects.SerializableLocation.asBukkitLocation(SerializableLocation.java:38) ~[?:?]
        at xzot1k.plugins.hd.api.TeleportationHandler.run(TeleportationHandler.java:115) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[Paper-latest.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[Paper-latest.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[Paper-latest.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[Paper-latest.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[Paper-latest.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[Paper-latest.jar:git-Paper-175]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[09:55:16 WARN]: [HyperDrive] Task #1245 for HyperDrive v5.1.8 generated an exception
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[Paper-latest.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.getWorld(CraftServer.java:1079) ~[Paper-latest.jar:git-Paper-175]
        at xzot1k.plugins.hd.api.objects.SerializableLocation.asBukkitLocation(SerializableLocation.java:38) ~[?:?]
        at xzot1k.plugins.hd.api.TeleportationHandler.run(TeleportationHandler.java:115) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[Paper-latest.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[Paper-latest.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[Paper-latest.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[Paper-latest.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[Paper-latest.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[Paper-latest.jar:git-Paper-175]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by XZot1K** [comment]
This error looks like a invalid world has appeared in one of the warps. This will be checked too, in the mean time i recommend opening the warps yml while the plugin is unloaded and just removing warps with invalid worlds. The converters were made to just convert the warps before hand and the new system didn't check for invalids. I will hopefully adjust this soon!
